In [1]:
from src.environment._ENV_move import Board
from src.agent._AGENT_move import Piece
from src.learn._monte_carlo import Monte_carlo
from src.learn._q_learning_move import Q_learning_move
from src.learn._td import Temporal_difference
from src.learn._td_lambda import Temporal_difference_lambda
from src.learn._policy_iteration import Policy_iteration
from src.learn._exp_td import Expected_temporal_difference
import torch



# env.render()


# Move chess
### Policy iteration

In [2]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
r = Policy_iteration(agent=p,env=env)
r.policy_iteration(k=1,gamma=1,synchronous=True)




Value function for this policy:
tensor([[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1,  0],
        [-1, -1, -1, -1, -1, -1, -1, -1]], dtype=torch.int32)

Value function for this policy:
tensor([[-9, -9, -9, -9, -9, -9, -9, -9],
        [-9, -9, -9, -9, -9, -9, -9, -9],
        [-9, -9, -9, -9, -9, -8, -8, -8],
        [-9, -9, -9, -9, -8, -8, -8, -7],
        [-9, -9, -9, -8, -8, -7, -6, -5],
        [-9, -9, -9, -8, -7, -6, -1, -1],
        [-9, -9, -9, -8, -7, -5, -1,  0],
        [-9, -9, -9, -8, -7, -5, -1, -1]], dtype=torch.int32)

Value function for this policy:
tensor([[-5, -5, -5, -5, -5, -5, -5, -5],
        [-5, -5, -4, -4, -4, -4, -4, -4],
        [-5, -5, -4, -3, -3, -3, -3, -3],
        [-5, -5, -4, -3, -3, -3, -3, -3],
        [-5, -5, -4, 

### SARSA temporal difference

In [2]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
td = Temporal_difference(p, env)
td.sarsa_td(n_episodes=1000, alpha=0.2, gamma=0.9)
td.visualize_policy() # controllare il risultato
td.visualize_action_function()
# r.TD_zero(epsilon=0.1, alpha=0.05, lamb=0.9)


Convergence reached at episode: 372
[['↘', '↘', '↑', '←', '←', '↖', '←', '↙'],
 ['↓', '↘', '↘', '↘', '↑', '↘', '↑', '↙'],
 ['↙', '↘', '↘', '↘', '↙', '↓', '↙', '↗'],
 ['→', '↘', '↓', '↘', '↘', '↘', '↓', '↙'],
 ['↖', '←', '↖', '↘', '→', '↘', '↘', '↑'],
 ['↙', '↘', '→', '↖', '→', '↘', '↘', '↓'],
 ['↙', '↙', '↑', '↗', '→', '←', '→', 'F'],
 ['↓', '↑', '→', '↙', '↗', '↗', '↗', '↑']]
Value function for this policy:
tensor([[-5, -4, -4, -3, -3, -3, -3, -3],
        [-4, -4, -4, -3, -3, -3, -3, -2],
        [-4, -4, -4, -3, -3, -3, -2, -2],
        [-4, -3, -3, -3, -2, -2, -2, -2],
        [-3, -3, -3, -3, -2, -1, -1, -1],
        [-3, -3, -3, -3, -2, -1,  0,  0],
        [-3, -3, -3, -2, -2, -1,  0,  0],
        [-3, -3, -3, -2, -2, -1,  0,  0]], dtype=torch.int32)


### Expected SARSA temporal difference

In [3]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
exp_tp = Expected_temporal_difference(agent=p, env=env)
exp_tp.expected_sarsa(n_episodes=1000, alpha=0.2, gamma=0.9)
# r.visualize_policy() # controllare il risultato
exp_tp.visualize_action_function()




Value function for this policy:
tensor([[-5, -5, -5, -4, -4, -3, -3, -3],
        [-5, -5, -4, -4, -4, -3, -3, -3],
        [-5, -4, -4, -4, -3, -3, -3, -3],
        [-4, -4, -4, -4, -3, -3, -2, -2],
        [-4, -4, -4, -3, -3, -2, -2, -2],
        [-4, -4, -3, -3, -2, -2,  0,  0],
        [-4, -3, -3, -3, -2, -2,  0,  0],
        [-3, -3, -3, -3, -2, -2,  0,  0]], dtype=torch.int32)


In [4]:
policy_diff = torch.norm(td.agent.action_function - exp_tp.agent.action_function)
print("Norm of Policy Difference:", policy_diff.item())

Norm of Policy Difference: 12.506937980651855


### Temporal difference lambda (da lasciare?)

In [5]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
td_lambda = Temporal_difference_lambda(agent=p, env=env)
td_lambda.sarsa_lambda(n_episodes=1000,alpha=0.2,gamma=0.9)
# td_lambda.visualize_policy() # controllare il risultato
td_lambda.visualize_action_function()


tensor([[-6, -5, -5, -5, -5, -4, -4, -3],
        [-6, -5, -5, -5, -5, -4, -4, -3],
        [-6, -5, -5, -4, -3, -3, -3, -3],
        [-5, -5, -4, -4, -3, -2, -3, -2],
        [-5, -5, -4, -3, -3, -2, -2, -2],
        [-4, -4, -4, -3, -2, -2,  0,  0],
        [-4, -4, -4, -3, -2, -2,  0,  0],
        [-4, -4, -4, -3, -2, -2,  0,  0]], dtype=torch.int32)


In [6]:
policy_diff = torch.norm(td.agent.action_function - td_lambda.agent.action_function)
print("Norm of Policy Difference:", policy_diff.item())

Norm of Policy Difference: 30.821823120117188


### Q-learning

In [7]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
q = Q_learning_move(agent=p, env=env)
q.q_learning(n_episodes=1000, alpha=0.2, gamma=0.9)
# q.visualize_policy() # controllare il risultato
q.visualize_action_function()


tensor([[-5, -4, -4, -4, -3, -3, -3, -3],
        [-4, -4, -4, -4, -3, -3, -3, -3],
        [-4, -4, -4, -3, -3, -3, -3, -2],
        [-4, -4, -3, -3, -2, -2, -2, -2],
        [-3, -3, -3, -3, -2, -1, -1, -1],
        [-3, -3, -3, -3, -2, -1,  0,  0],
        [-3, -3, -3, -3, -2, -1,  0,  0],
        [-3, -3, -3, -2, -2, -1,  0,  0]], dtype=torch.int32)


In [8]:
policy_diff = torch.norm(td.agent.action_function - q.agent.action_function)
print("Norm of Policy Difference:", policy_diff.item())

Norm of Policy Difference: 5.995652198791504


### Monte Carlo Control

In [10]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
mc = Monte_carlo(agent=p, env=env)
for k in range(1000):
    eps = 0.5
    mc.monte_carlo_learning(epsilon=eps)
# r.visualize_policy() # controllare il risultato

print(torch.max(mc.agent.action_function, dim=2)[0].to(torch.int))

tensor([[-20, -53, -36, -15, -35, -15, -24, -14],
        [-21, -40, -19,  -9, -13, -26, -26, -15],
        [-30, -19, -28, -13,  -8, -20, -12, -14],
        [-26, -17, -26,  -7,  -9,  -8,  -6,  -4],
        [-19, -29,  -7, -18,  -3,  -8,  -4,  -2],
        [-26, -23, -24,  -6,  -9,  -3,  -1,  -1],
        [-28, -12, -13, -18,  -8,  -7,  -1,   0],
        [-35, -29,  -5, -24,  -3,  -3,  -1,  -1]], dtype=torch.int32)


In [11]:
policy_diff = torch.norm(td.agent.action_function - mc.agent.action_function)
print("Norm of Policy Difference:", policy_diff.item())

Norm of Policy Difference: 988.563232421875
