In [1]:
from src.environment._ENV_move import Board
from src.agent._AGENT_move import Piece
from src.learn._monte_carlo import Monte_carlo
from src.learn._q_learning_move import Q_learning_move
from src.learn._td import Temporal_difference
from src.learn._td_lambda import Temporal_difference_lambda
from src.learn._policy_iteration import Policy_iteration
from src.learn._exp_td import Expected_temporal_difference
import torch

env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"

# env.render()


# Move chess
### Policy iteration

In [2]:

r = Policy_iteration(agent=p,env=env)
r.policy_iteration(k=1,gamma=1,synchronous=True)




Value function for this policy:
tensor([[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1,  0],
        [-1, -1, -1, -1, -1, -1, -1, -1]], dtype=torch.int32)

Value function for this policy:
tensor([[-9, -9, -9, -9, -9, -9, -9, -9],
        [-9, -9, -9, -9, -9, -9, -9, -9],
        [-9, -9, -9, -9, -9, -8, -8, -8],
        [-9, -9, -9, -9, -8, -8, -8, -7],
        [-9, -9, -9, -8, -8, -7, -6, -5],
        [-9, -9, -9, -8, -7, -6, -1, -1],
        [-9, -9, -9, -8, -7, -5, -1,  0],
        [-9, -9, -9, -8, -7, -5, -1, -1]], dtype=torch.int32)

Value function for this policy:
tensor([[-5, -5, -5, -5, -5, -5, -5, -5],
        [-5, -5, -4, -4, -4, -4, -4, -4],
        [-5, -5, -4, -3, -3, -3, -3, -3],
        [-5, -5, -4, -3, -3, -3, -3, -3],
        [-5, -5, -4, 

### SARSA temporal difference

In [3]:
r = Temporal_difference(p, env)
r.sarsa_td(n_episodes=10000, alpha=0.2, gamma=0.9)
# r.visualize_policy() # controllare il risultato
r.visualize_action_function()
# r.TD_zero(epsilon=0.1, alpha=0.05, lamb=0.9)


Value function for this policy:
tensor([[-5, -5, -4, -4, -4, -3, -3, -3],
        [-5, -4, -4, -4, -4, -3, -3, -3],
        [-5, -4, -4, -3, -3, -3, -3, -3],
        [-4, -4, -4, -3, -3, -2, -2, -2],
        [-4, -4, -4, -3, -2, -1, -1, -1],
        [-4, -4, -3, -3, -2, -1,  0,  0],
        [-4, -3, -3, -3, -2, -1,  0,  0],
        [-3, -3, -3, -3, -2, -1,  0,  0]], dtype=torch.int32)


### Expected SARSA temporal difference

In [4]:

r = Expected_temporal_difference(agent=p, env=env)
r.expected_sarsa(n_episodes=10000, alpha=0.2, gamma=0.9)
# r.visualize_policy() # controllare il risultato
r.visualize_action_function()




Value function for this policy:
tensor([[-7, -6, -6, -5, -5, -4, -4, -4],
        [-6, -6, -5, -5, -5, -4, -4, -4],
        [-6, -6, -5, -5, -4, -4, -4, -4],
        [-5, -5, -5, -5, -4, -3, -3, -3],
        [-5, -5, -5, -4, -3, -2, -2, -2],
        [-5, -5, -4, -4, -3, -2,  0,  0],
        [-4, -4, -4, -4, -3, -2,  0,  0],
        [-4, -4, -4, -4, -3, -2,  0,  0]], dtype=torch.int32)


### Temporal difference lambda (da lasciare?)

In [5]:

r = Temporal_difference_lambda(agent=p, env=env)
r.sarsa_lambda(n_episodes=10000,alpha=0.2,gamma=0.9)
# r.visualize_policy() # controllare il risultato
r.visualize_action_function()


tensor([[-6, -5, -5, -5, -5, -5, -5, -4],
        [-6, -5, -5, -4, -4, -4, -4, -5],
        [-6, -5, -4, -4, -3, -3, -3, -4],
        [-5, -5, -4, -3, -3, -3, -2, -3],
        [-5, -5, -4, -4, -3, -2, -2, -2],
        [-5, -5, -4, -3, -3, -2,  0,  0],
        [-5, -5, -4, -3, -3, -2,  0,  0],
        [-5, -5, -4, -3, -3, -2,  0,  0]], dtype=torch.int32)


### Q-learning

In [6]:

r = Q_learning_move(agent=p, env=env)
r.q_learning(n_episodes=10000, alpha=0.2, gamma=0.9)
# r.visualize_policy() # controllare il risultato
r.visualize_action_function()


tensor([[-5, -5, -4, -4, -4, -5, -4, -4],
        [-5, -4, -4, -4, -4, -4, -4, -5],
        [-5, -4, -4, -3, -3, -3, -3, -3],
        [-5, -4, -4, -3, -2, -2, -2, -2],
        [-5, -4, -4, -3, -2, -1, -1, -1],
        [-5, -5, -4, -3, -2, -1,  0,  0],
        [-5, -5, -4, -3, -2, -1,  0,  0],
        [-5, -5, -4, -3, -2, -1,  0,  0]], dtype=torch.int32)


### Monte Carlo Control

In [7]:

r = Monte_carlo(agent=p, env=env)
for k in range(10000):
    eps = 0.5
    r.monte_carlo_learning(epsilon=eps)
# r.visualize_policy() # controllare il risultato

print(torch.max(r.agent.action_function, dim=2)[0].to(torch.int))

tensor([[-15, -23, -24, -15, -16, -22, -18, -17],
        [-19, -21, -19, -11, -19, -17, -18, -17],
        [-26, -25, -18, -20,  -8, -11, -13, -12],
        [-24, -22, -16, -10,  -9,  -8,  -6,  -8],
        [-21, -13, -11,  -8,  -7,  -4,  -3,  -3],
        [-15, -17, -10,  -6,  -3,  -4,  -1,  -1],
        [-26, -23, -16, -11,  -6,  -3,  -1,   0],
        [-19, -10, -17, -11,  -4,  -2,  -1,  -1]], dtype=torch.int32)
