In [1]:
from src.environment._ENV_move import Board
from src.agent._AGENT_move import Piece

from src.learn._q_learning_move import Q_learning_move
from src.learn._td import Temporal_difference
from src.learn._td_lambda import Temporal_difference_lambda
from src.learn._policy_iteration import Policy_iteration
from src.learn._exp_td import Expected_temporal_difference
import torch

# Move chess
### Policy iteration

In [5]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
r = Policy_iteration(agent=p,env=env)
# r.policy_iteration(k=1,gamma=1,synchronous=True)
# # r.visualize_policy()

# print(r.calculate_cumulative_rewards(num_episodes=100))

aaa = []
for _ in range(10):

    policy_iter_rewards = r.run_episode()


print(len(policy_iter_rewards))
print(policy_iter_rewards)


100
[tensor(-65.), tensor(-187.), tensor(-105.), tensor(-98.), tensor(-227.), tensor(-160.), tensor(-133.), tensor(-148.), tensor(-88.), tensor(-55.), tensor(-27.), tensor(-47.), tensor(-143.), tensor(-20.), tensor(-31.), tensor(-158.), tensor(-26.), tensor(-54.), tensor(-90.), tensor(-64.), tensor(-19.), tensor(-81.), tensor(-61.), tensor(-194.), tensor(-44.), tensor(-62.), tensor(-37.), tensor(-44.), tensor(-80.), tensor(-51.), tensor(-68.), tensor(-13.), tensor(-18.), tensor(-32.), tensor(-12.), tensor(-9.), tensor(-61.), tensor(-76.), tensor(-12.), tensor(-13.), tensor(-10.), tensor(-17.), tensor(-28.), tensor(-17.), tensor(-9.), tensor(-11.), tensor(-11.), tensor(-22.), tensor(-9.), tensor(-7.), tensor(-8.), tensor(-9.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-9.), tensor(-10.), tensor(-8.), tensor(-8.), tensor(-8.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-7.), tensor(-7.), ten

### SARSA temporal difference

In [3]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
td = Temporal_difference(p, env)
td_cum_reward = td.sarsa_td(n_episodes=1000, alpha=0.2, gamma=0.9)
# td.visualize_policy() # controllare il risultato
# td.visualize_action_function()



(-1, 0)
(-1, 0)
(0, 1)
(-1, 1)
(0, 1)
(-1, 0)
(-1, 0)
(0, 1)
(1, 1)
(-1, 0)
(1, -1)
(1, 0)
(0, -1)
(0, -1)
(0, -1)
(0, -1)
(0, -1)
(1, 1)
(1, 0)
(0, 1)
(-1, -1)
(-1, -1)
(0, 1)
(1, -1)
(-1, -1)
(1, 1)
(-1, -1)
(1, 0)
(-1, 0)
(1, 1)
(-1, -1)
(1, -1)
(0, -1)
(-1, 0)
(-1, 1)
(0, 1)
(0, -1)
(1, 1)
(0, 1)
(0, -1)
(0, -1)
(1, -1)
(1, 0)
(1, -1)
(0, -1)
(-1, 0)
(1, 0)
(-1, 0)
(1, 0)
(1, -1)
(-1, 1)
(0, 1)
(-1, -1)
(0, 1)
(1, 0)
(0, -1)
(-1, -1)
(1, 1)
(1, 1)
(1, -1)
(1, 0)
(0, -1)
(-1, -1)
(-1, -1)
(-1, 0)
(1, -1)
(1, 1)
(1, -1)
(-1, -1)
(-1, -1)
(1, 1)
(-1, 0)
(1, -1)
(-1, 0)
(1, 0)
(1, 1)
(-1, 0)
(-1, 1)
(1, 0)
(1, 0)
(1, -1)
(1, 0)
(1, 1)
(-1, -1)
(-1, 1)
(1, 0)
(1, 1)
(0, 1)
(0, -1)
(-1, 1)
(0, 1)
(1, 0)
(0, -1)
(1, 0)
(1, -1)
(-1, 1)
(1, -1)
(-1, -1)
(0, -1)
(1, -1)
(-1, 1)
(1, 0)
(1, 1)
(1, -1)
(1, -1)
(1, 1)
(-1, 1)
(0, -1)
(1, 1)
(1, -1)
(0, -1)
(1, 1)
(-1, 0)
(1, -1)
(0, -1)
(-1, 0)
(0, 1)
(0, -1)
(0, 1)
(-1, 0)
(-1, 1)
(1, -1)
(-1, 0)
(-1, 1)
(-1, -1)
(1, 1)
(1, 1)
(0, -1)
(0, -1)
(

### Expected SARSA temporal difference

In [4]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
exp_tp = Expected_temporal_difference(agent=p, env=env)
exp_tp.expected_sarsa(n_episodes=1000, alpha=0.2, gamma=0.9)
exp_tp.visualize_policy() # controllare il risultato
exp_tp.visualize_action_function()


[['↘', '↘', '↓', '↓', '↘', '↓', '↑', '→'],
 ['↘', '↘', '←', '→', '↘', '↘', '↙', '↖'],
 ['↓', '→', '↘', '↘', '↘', '↘', '↓', '→'],
 ['↓', '↘', '←', '↘', '↘', '↘', '↗', '→'],
 ['↙', '↑', '↑', '↘', '↘', '↘', '↘', '↓'],
 ['↗', '↘', '↘', '←', '↘', '↘', '↘', '↓'],
 ['↘', '↘', '↘', '→', '→', '↘', '→', 'F'],
 ['↘', '↖', '↘', '↗', '↗', '↓', '↗', '←']]
Value function for this policy:
tensor([[-5, -5, -5, -4, -4, -3, -3, -3],
        [-5, -5, -4, -4, -4, -3, -3, -3],
        [-5, -5, -4, -4, -3, -3, -3, -3],
        [-4, -4, -4, -4, -3, -2, -2, -2],
        [-4, -4, -4, -3, -3, -2, -2, -2],
        [-4, -4, -3, -3, -2, -2,  0,  0],
        [-4, -3, -3, -3, -2, -1,  0,  0],
        [-3, -3, -3, -3, -2, -1,  0,  0]], dtype=torch.int32)


In [5]:
policy_diff = torch.norm(td.agent.action_function - exp_tp.agent.action_function)
print("Norm of Policy Difference:", policy_diff.item())

Norm of Policy Difference: 9.62839412689209


### Temporal difference lambda (da lasciare?)

In [6]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
td_lambda = Temporal_difference_lambda(agent=p, env=env)
td_lambda.sarsa_lambda(n_episodes=1000,alpha=0.2,gamma=0.9)
# td_lambda.visualize_policy() # controllare il risultato
td_lambda.visualize_action_function()


tensor([[-5, -6, -5, -5, -4, -4, -4, -3],
        [-6, -5, -5, -4, -4, -4, -3, -3],
        [-6, -5, -4, -4, -4, -3, -3, -3],
        [-5, -5, -4, -3, -3, -3, -2, -2],
        [-5, -5, -4, -3, -3, -2, -2, -1],
        [-4, -4, -4, -3, -3, -2,  0,  0],
        [-4, -4, -3, -3, -3, -2,  0,  0],
        [-4, -4, -3, -3, -2, -1,  0,  0]], dtype=torch.int32)


In [7]:
policy_diff = torch.norm(td.agent.action_function - td_lambda.agent.action_function)
print("Norm of Policy Difference:", policy_diff.item())

Norm of Policy Difference: 24.19397735595703


### Q-learning

In [8]:
env = Board()
p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
q = Q_learning_move(agent=p, env=env)
q.q_learning(n_episodes=1000, alpha=0.2, gamma=0.9)
q.visualize_policy() # controllare il risultato
q.visualize_action_function()


[['→', '↘', '↘', '→', '↓', '↘', '↓', '↖'],
 ['→', '→', '↘', '→', '↑', '↑', '↗', '→'],
 ['↓', '↘', '→', '↘', '↘', '↘', '↖', '←'],
 ['↘', '↙', '↘', '→', '↘', '↘', '↘', '↗'],
 ['↓', '↗', '↗', '→', '→', '↘', '↓', '↓'],
 ['↑', '↘', '↘', '→', '→', '→', '↘', '↓'],
 ['→', '↘', '↖', '↘', '→', '↗', '→', 'F'],
 ['↓', '→', '↓', '↓', '↙', '↗', '↗', '↑']]
tensor([[-5, -4, -4, -4, -3, -3, -3, -3],
        [-4, -4, -4, -4, -3, -3, -3, -3],
        [-4, -4, -4, -3, -3, -3, -3, -2],
        [-4, -4, -3, -3, -2, -2, -2, -2],
        [-4, -3, -3, -3, -2, -1, -1, -1],
        [-3, -3, -3, -3, -2, -1,  0,  0],
        [-3, -3, -3, -3, -2, -1,  0,  0],
        [-3, -3, -3, -3, -2, -1,  0,  0]], dtype=torch.int32)


In [9]:
policy_diff = torch.norm(td.agent.action_function - q.agent.action_function)
print("Norm of Policy Difference:", policy_diff.item())

Norm of Policy Difference: 2.9951775074005127


## Evaluation of algorithms

In [8]:
import time
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm

a_env = Board()
a_p = Piece(piece='king')
b_env = Board()
b_p = Piece(piece='king')
c_env = Board()
c_p = Piece(piece='king')
d_env = Board()
d_p = Piece(piece='king')
e_env = Board()
e_p = Piece(piece='king')
f_env = Board()
f_p = Piece(piece='king')

algorithms = [
    Policy_iteration(agent=f_p, env=f_env),
    Q_learning_move(env=a_env, agent=a_p),
    Temporal_difference(agent=b_p, env=b_env),
    Temporal_difference_lambda(agent=c_p, env=c_env),
    Expected_temporal_difference(agent=e_p, env=e_env),
    
]

results = []
n_of_episodes = 1000

for algorithm in tqdm(algorithms):
    
    start_time = time.time()
    rewards = []
    if type(algorithm).__name__ != 'Policy_iteration':
        for episode in range(n_of_episodes):
            reward = algorithm.run_episode(episode)  # this function should return the total reward for the episode
            rewards.append(reward)
    
    else:
        for episode in range(n_of_episodes//10):  # ahhh boh
            reward = algorithm.run_episode(n_of_episodes)
        rewards = reward
    
    end_time = time.time()
    
    results.append({
        'name': type(algorithm).__name__,
        'rewards': rewards,
        'time': end_time - start_time,
    })

#     print(len(rewards))

# print(results)

# Plot average cumulative reward
for result in results:
    plt.plot(np.cumsum(result['rewards']) / np.arange(1, n_of_episodes+1), label=result['name'])
plt.legend()
plt.title('Average Cumulative Reward')
plt.show()

# Print time taken
for result in results:
    print(f"{result['name']} took {result['time']} seconds")

100%|██████████| 5/5 [00:45<00:00,  9.05s/it]


Policy_iteration took 4.222756624221802 seconds
Q_learning_move took 9.123284578323364 seconds
Temporal_difference took 17.01800847053528 seconds
Temporal_difference_lambda took 2.996976613998413 seconds
Expected_temporal_difference took 11.896793365478516 seconds


In [14]:
import time
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm

n_of_episodes = 1000
results = []

for g in tqdm([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]):
# for g in [0.9]:
    rewards = []
    env = Board()
    p = Piece(piece='king')  # king", "rook", "bishop" or "knight"
    q = Q_learning_move(agent=p, env=env)
    
    for episode in range(n_of_episodes):
        reward = q.run_episode(episode, gamma=g)  # this function should return the total reward for the episode
        rewards.append(reward)

    results.append({
        'name': g,
        'rewards': rewards
    })

# Plot average cumulative reward
for result in results:
    plt.plot(np.cumsum(result['rewards']) / np.arange(1, n_of_episodes+1), label=result['name'])
plt.legend()
plt.show()



100%|██████████| 9/9 [01:29<00:00,  9.94s/it]
